name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Node.js App
      - uses: actions/checkout@v2
        run: npm install
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}
          script: |
            cd /var/www/orders_server
            git pull origin main
            NODE_ENV=prod
            npm start

