on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v2
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: NODE_ENV=prod
      - run: npm start
